name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: jessie

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      with:
        arch: armv7
        distro: jessie
        run: docker build . --file Dockerfile --tag opencv-python3.7:$(date +%s)
